### ISSUE TITLE
Memasukkan data KOL ke dalam Dashboard

### ISSUE THREAD

**Issue by alfarabitommy** [alfarabitommy/smm#3]
Data dari master KOL dimasukkan ke dalam dashboard utama admin
<img width="1003" alt="Screen Shot 2024-03-12 at 23 46 46" src="https://github.com/alfarabitommy/smm/assets/88763453/00926201-252b-4ade-894f-3e6c55b48d55">

Poin 1
Berisi total akumulasi KOL yang terdapat pada master data KOL

Poin 2
Berisi semua akumulasi followers baik dari tiktok maupun instagram

Poin 3
Berisi produk yang paling banyak muncul diantara produk - produk lainnya (kemungkinan besok gua buatin master produknya sih ki)

Poin 4
Sama seperti poin 3, namun berisi produk yang paling jarang muncul

Poin 5
Akumulasi data social media, apakah tiktok / instagram (jika dalam field ada keduanya, maka masing masing terhitung 1) (ini kemungkinan bakal gua bikin radio button sih kedepannya)

Poin 6
Grafik produk yang muncul (ini juga nanti akan gue buatin masternya sih kemungkinan, biar lebih gampang)

Untuk petunjuk gambarannya seperti gambar dibawah ya ki
<img width="1011" alt="Screen Shot 2024-03-12 at 23 49 45" src="https://github.com/alfarabitommy/smm/assets/88763453/99f06589-072c-4b66-a2fd-df0ae858ac93">

**Comment by muhammad-rifqi** [comment]
OKE TOM

**Comment by alfarabitommy** [comment]
Ahsiap kiii

**Comment by muhammad-rifqi** [comment]
BERARTI GUA NUNGGU LU SELESAI NGERJAIN CRUD YA TOM, SAMA LU JUGA PUSH DB BARU NANTI YA

**Comment by muhammad-rifqi** [comment]
udah beres ya bossque, di pull aja

**Comment by alfarabitommy** [comment]
Waaah, siap2 thankyou bosquee...

**Comment by muhammad-rifqi** [comment]
jangan lupa DB nya nanti yaak bossque. kalau mau di push. :)

**Comment by alfarabitommy** [comment]
Oh oke siaaap, biar kita DBnya sinkron gmn ya ki
