### ISSUE TITLE
Editan di KOL

### ISSUE THREAD

**Issue by alfarabitommy** [alfarabitommy/smm#4]
Jadi ketika ngedit data, untuk dropdownnya masih salah
<img width="698" alt="Screen Shot 2024-03-14 at 14 39 51" src="https://github.com/alfarabitommy/smm/assets/88763453/e1ef30ab-0954-4345-85ae-b16523712207">

Datanya sih masuk ke DB, tapi dropdownnya yg muncul itu terus hahahah

**Comment by muhammad-rifqi** [comment]
urusan remote DB udah gua share di wa, cuma case ini yang pasti lu push dulu DB nya. soalnya di gua pasti add aja ngga berhasil.

**Comment by muhammad-rifqi** [comment]
Sudah Ya bossque. di pull lagi aja
