### ISSUE TITLE
Radio Button di Add dan Edit KOL

### ISSUE THREAD

**Issue by alfarabitommy** [alfarabitommy/smm#5]
<img width="694" alt="Screen Shot 2024-03-20 at 21 36 22" src="https://github.com/alfarabitommy/smm/assets/88763453/098abebe-df6a-4a8e-8b48-b639b3593499">
<br>
Bosque, untuk add sama edit udah gua lengkapin bosque, palingan yg belum tinggal radio button yang gua ss diatas bosque, tadi gua coba2 tapi masih mentok bosque.
Udah kelamaan kaga buka keknya, hahaha.
Thx bosqueee...

**Comment by muhammad-rifqi** [comment]
siap bossque

**Comment by alfarabitommy** [comment]
Thankyouuu bosquee

**Comment by muhammad-rifqi** [comment]
Database nya jangan lupa bossque !!

**Comment by alfarabitommy** [comment]
Siap bosquee, udah gua kirim ya bosqueee
